type AppEnv = {
  REACT_APP_BACKEND_URL: string;
  REACT_APP_FACEBOOK_APP_ID: string;
  REACT_APP_REQUIRE_BUSINESS_MANAGEMENT: boolean;
  REACT_APP_NAME_SYSTEM: string;
  REACT_APP_NUMBER_SUPPORT: string;
  REACT_APP_HOURS_CLOSE_TICKETS_AUTO: string;
  REACT_APP_PRIMARY_COLOR: string;
  REACT_APP_PRIMARY_DARK: string;
};
const env: AppEnv = {
  REACT_APP_BACKEND_URL: (process.env.REACT_APP_BACKEND_URL as string) || "",
  REACT_APP_FACEBOOK_APP_ID: (process.env.REACT_APP_FACEBOOK_APP_ID as string) || "",
  REACT_APP_REQUIRE_BUSINESS_MANAGEMENT: (((process.env.REACT_APP_REQUIRE_BUSINESS_MANAGEMENT as string) || "FALSE").toUpperCase() === "TRUE"),
  REACT_APP_NAME_SYSTEM: (process.env.REACT_APP_NAME_SYSTEM as string) || "Gissap CRM",
  REACT_APP_NUMBER_SUPPORT: (process.env.REACT_APP_NUMBER_SUPPORT as string) || "",
  REACT_APP_HOURS_CLOSE_TICKETS_AUTO: (process.env.REACT_APP_HOURS_CLOSE_TICKETS_AUTO as string) || "9999",
  REACT_APP_PRIMARY_COLOR: (process.env.REACT_APP_PRIMARY_COLOR as string) || "#06b6d4",
  REACT_APP_PRIMARY_DARK: (process.env.REACT_APP_PRIMARY_DARK as string) || "#3b82f6"
};
export default env;
export const BACKEND_URL: string = env.REACT_APP_BACKEND_URL;
export const FACEBOOK_APP_ID: string = env.REACT_APP_FACEBOOK_APP_ID;
export const REQUIRE_BUSINESS_MANAGEMENT: boolean = env.REACT_APP_REQUIRE_BUSINESS_MANAGEMENT;
export const NAME_SYSTEM: string = env.REACT_APP_NAME_SYSTEM;
export const NUMBER_SUPPORT: string = env.REACT_APP_NUMBER_SUPPORT;
export const HOURS_CLOSE_TICKETS_AUTO: string = env.REACT_APP_HOURS_CLOSE_TICKETS_AUTO;
export const PRIMARY_COLOR: string = env.REACT_APP_PRIMARY_COLOR;
export const PRIMARY_DARK: string = env.REACT_APP_PRIMARY_DARK;
